SET DEFINE OFF;

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'STUDENT' NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('STUDENT', 'CREATOR', 'MENTOR', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);

CREATE TABLE universities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    country VARCHAR2(100),
    city VARCHAR2(100),
    website_url VARCHAR2(500),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_universities PRIMARY KEY (id),
    CONSTRAINT uq_universities_name UNIQUE (name)
);

CREATE TABLE academic_fields (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_academic_fields PRIMARY KEY (id),
    CONSTRAINT uq_academic_fields_name UNIQUE (name)
);

CREATE TABLE students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    university_id NUMBER NOT NULL,
    academic_field_id NUMBER NOT NULL,
    department VARCHAR2(255),
    semester VARCHAR2(50),
    skill_level VARCHAR2(20) NOT NULL,
    bio CLOB,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (id),
    CONSTRAINT uq_students_user UNIQUE (user_id),
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_students_university FOREIGN KEY (university_id) REFERENCES universities (id),
    CONSTRAINT fk_students_field FOREIGN KEY (academic_field_id) REFERENCES academic_fields (id),
    CONSTRAINT ck_students_skill CHECK (skill_level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED'))
);

CREATE TABLE student_preferences (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id NUMBER NOT NULL,
    goal_type VARCHAR2(30) NOT NULL,
    preference_key VARCHAR2(255) NOT NULL,
    preference_value VARCHAR2(1000),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_student_preferences PRIMARY KEY (id),
    CONSTRAINT fk_stud_pref_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT ck_stud_pref_goal CHECK (goal_type IN ('ASSIGNMENT', 'RESEARCH', 'LAB', 'CODING', 'EXAM', 'PROJECT'))
);

CREATE TABLE academic_documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    document_type VARCHAR2(30) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    file_path VARCHAR2(1000),
    file_mime_type VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'UPLOADED' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_academic_documents PRIMARY KEY (id),
    CONSTRAINT fk_acad_docs_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT ck_acad_docs_type CHECK (document_type IN ('CURRICULUM', 'ROUTINE', 'SYLLABUS', 'ASSIGNMENT', 'LAB_FILE', 'RESEARCH_PAPER', 'COURSE_OUTLINE', 'OTHER')),
    CONSTRAINT ck_acad_docs_status CHECK (status IN ('UPLOADED', 'EXTRACTED', 'FAILED'))
);

CREATE TABLE extracted_document_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    document_id NUMBER NOT NULL,
    student_id NUMBER NOT NULL,
    data_type VARCHAR2(30) NOT NULL,
    data_key VARCHAR2(255) NOT NULL,
    data_value CLOB,
    confidence_score NUMBER(3,2) DEFAULT 0,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_extracted_document_data PRIMARY KEY (id),
    CONSTRAINT fk_ext_data_document FOREIGN KEY (document_id) REFERENCES academic_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_ext_data_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT ck_ext_data_type CHECK (data_type IN ('SUBJECT', 'TOPIC', 'DEADLINE', 'ROUTINE_SLOT', 'RESOURCE_NAME', 'RESEARCH_AREA', 'KEYWORD')),
    CONSTRAINT ck_ext_data_conf CHECK (confidence_score BETWEEN 0 AND 1)
);

CREATE TABLE academic_tasks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_academic_tasks PRIMARY KEY (id),
    CONSTRAINT uq_academic_tasks_name UNIQUE (name)
);

CREATE TABLE tool_categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_tool_categories PRIMARY KEY (id),
    CONSTRAINT uq_tool_categories_name UNIQUE (name)
);

CREATE TABLE tools (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tool_category_id NUMBER NOT NULL,
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    website_url VARCHAR2(500),
    academic_field_id NUMBER,
    task_id NUMBER,
    is_free NUMBER(1) DEFAULT 1 NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_tools PRIMARY KEY (id),
    CONSTRAINT fk_tools_category FOREIGN KEY (tool_category_id) REFERENCES tool_categories (id),
    CONSTRAINT fk_tools_field FOREIGN KEY (academic_field_id) REFERENCES academic_fields (id),
    CONSTRAINT fk_tools_task FOREIGN KEY (task_id) REFERENCES academic_tasks (id),
    CONSTRAINT ck_tools_free CHECK (is_free IN (0, 1)),
    CONSTRAINT ck_tools_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE resource_categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_resource_categories PRIMARY KEY (id),
    CONSTRAINT uq_resource_cat_name UNIQUE (name)
);

CREATE TABLE resources (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resource_category_id NUMBER NOT NULL,
    academic_field_id NUMBER,
    task_id NUMBER,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    resource_url VARCHAR2(1000) NOT NULL,
    difficulty_level VARCHAR2(20) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    save_count NUMBER DEFAULT 0 NOT NULL,
    average_rating NUMBER(3,2) DEFAULT 0 NOT NULL,
    created_by NUMBER,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_resources PRIMARY KEY (id),
    CONSTRAINT fk_resources_category FOREIGN KEY (resource_category_id) REFERENCES resource_categories (id),
    CONSTRAINT fk_resources_field FOREIGN KEY (academic_field_id) REFERENCES academic_fields (id),
    CONSTRAINT fk_resources_task FOREIGN KEY (task_id) REFERENCES academic_tasks (id),
    CONSTRAINT fk_resources_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_resources_difficulty CHECK (difficulty_level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT ck_resources_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_resources_save_count CHECK (save_count >= 0),
    CONSTRAINT ck_resources_avg_rating CHECK (average_rating BETWEEN 0 AND 5)
);

CREATE TABLE template_categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_template_categories PRIMARY KEY (id),
    CONSTRAINT uq_template_cat_name UNIQUE (name)
);

CREATE TABLE templates (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    template_category_id NUMBER NOT NULL,
    university_id NUMBER,
    academic_field_id NUMBER,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    template_url VARCHAR2(1000) NOT NULL,
    price NUMBER(10,2) DEFAULT 0 NOT NULL,
    is_paid NUMBER(1) DEFAULT 0 NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    download_count NUMBER DEFAULT 0 NOT NULL,
    average_rating NUMBER(3,2) DEFAULT 0 NOT NULL,
    created_by NUMBER,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_templates PRIMARY KEY (id),
    CONSTRAINT fk_templates_category FOREIGN KEY (template_category_id) REFERENCES template_categories (id),
    CONSTRAINT fk_templates_university FOREIGN KEY (university_id) REFERENCES universities (id),
    CONSTRAINT fk_templates_field FOREIGN KEY (academic_field_id) REFERENCES academic_fields (id),
    CONSTRAINT fk_templates_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_templates_price CHECK (price >= 0),
    CONSTRAINT ck_templates_paid CHECK (is_paid IN (0, 1)),
    CONSTRAINT ck_templates_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_templates_downloads CHECK (download_count >= 0),
    CONSTRAINT ck_templates_avg_rating CHECK (average_rating BETWEEN 0 AND 5)
);

CREATE TABLE saved_resources (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id NUMBER NOT NULL,
    resource_id NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_saved_resources PRIMARY KEY (id),
    CONSTRAINT fk_saved_res_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_res_resource FOREIGN KEY (resource_id) REFERENCES resources (id) ON DELETE CASCADE,
    CONSTRAINT uq_saved_res_student_resource UNIQUE (student_id, resource_id)
);

CREATE TABLE saved_templates (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id NUMBER NOT NULL,
    template_id NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_saved_templates PRIMARY KEY (id),
    CONSTRAINT fk_saved_tmpl_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_tmpl_template FOREIGN KEY (template_id) REFERENCES templates (id) ON DELETE CASCADE,
    CONSTRAINT uq_saved_tmpl_student_tmpl UNIQUE (student_id, template_id)
);

CREATE TABLE template_purchases (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id NUMBER NOT NULL,
    template_id NUMBER NOT NULL,
    amount NUMBER(10,2) DEFAULT 0 NOT NULL,
    payment_status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_template_purchases PRIMARY KEY (id),
    CONSTRAINT fk_tmpl_purch_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT fk_tmpl_purch_template FOREIGN KEY (template_id) REFERENCES templates (id) ON DELETE CASCADE,
    CONSTRAINT ck_tmpl_purch_amount CHECK (amount >= 0),
    CONSTRAINT ck_tmpl_purch_status CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED'))
);

CREATE TABLE research_topics (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    academic_field_id NUMBER,
    status VARCHAR2(20) DEFAULT 'IDEA' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_research_topics PRIMARY KEY (id),
    CONSTRAINT fk_research_topics_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT fk_research_topics_field FOREIGN KEY (academic_field_id) REFERENCES academic_fields (id),
    CONSTRAINT ck_research_topics_status CHECK (status IN ('IDEA', 'READING', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE TABLE research_collections (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    research_topic_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    collection_type VARCHAR2(20) NOT NULL,
    resource_url VARCHAR2(1000),
    summary CLOB,
    keywords VARCHAR2(1000),
    reading_status VARCHAR2(20) DEFAULT 'TO_READ' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_research_collections PRIMARY KEY (id),
    CONSTRAINT fk_research_coll_topic FOREIGN KEY (research_topic_id) REFERENCES research_topics (id) ON DELETE CASCADE,
    CONSTRAINT ck_research_coll_type CHECK (collection_type IN ('PAPER', 'DATASET', 'LINK', 'NOTE', 'VIDEO')),
    CONSTRAINT ck_research_coll_status CHECK (reading_status IN ('TO_READ', 'READING', 'READ', 'IMPORTANT'))
);

CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id NUMBER NOT NULL,
    reviewable_type VARCHAR2(20) NOT NULL,
    reviewable_id NUMBER NOT NULL,
    rating NUMBER(1) NOT NULL,
    comment_text CLOB,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT fk_reviews_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT ck_reviews_type CHECK (reviewable_type IN ('RESOURCE', 'TEMPLATE', 'TOOL')),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    table_name VARCHAR2(100) NOT NULL,
    record_id NUMBER NOT NULL,
    action_type VARCHAR2(20) NOT NULL,
    old_value CLOB,
    new_value CLOB,
    changed_by NUMBER,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT fk_audit_changed_by FOREIGN KEY (changed_by) REFERENCES users (id),
    CONSTRAINT ck_audit_action_type CHECK (action_type IN ('INSERT', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT'))
);

CREATE INDEX idx_students_university ON students (university_id);
CREATE INDEX idx_students_field ON students (academic_field_id);
CREATE INDEX idx_documents_student ON academic_documents (student_id);
CREATE INDEX idx_resources_status ON resources (status);
CREATE INDEX idx_resources_field ON resources (academic_field_id);
CREATE INDEX idx_templates_status ON templates (status);
CREATE INDEX idx_templates_field ON templates (academic_field_id);
CREATE INDEX idx_research_student ON research_topics (student_id);
CREATE INDEX idx_reviews_reviewable ON reviews (reviewable_type, reviewable_id);

COMMIT;
